# **Aprendendo sobre clusters com Alura**
<center>
<img src="../img/andreson.png" />
</center>

**Autor:** Andreson Almeida Azevedo

In [1]:
# dados
import pandas as pd
import numpy as np

# pre-processamento
from sklearn.preprocessing import Normalizer

# algoritmos cluster
from sklearn.cluster import KMeans
from sklearn_extra.cluster import KMedoids
from sklearn.cluster import DBSCAN
# k-vizinhos mais próximos
from sklearn.neighbors import NearestNeighbors

# métricas de validação
from sklearn.metrics import silhouette_score
from sklearn.metrics import davies_bouldin_score
from sklearn.metrics import calinski_harabasz_score

# Visualizações
import matplotlib.pyplot as plt
import seaborn as sns

# salvar e carregar modelo

import pickle

# carregar datasets
from sklearn import datasets

In [2]:
def clustering_algorithm(n_clusters, df_ref, n_init = 10, max_iter = 300, random_state = 101):
    kmeans = KMeans(n_clusters=n_clusters, n_init=n_init, max_iter=max_iter, random_state=random_state)
    labels = kmeans.fit_predict(df_ref)
    s = silhouette_score(df_ref, labels, metric="euclidean")
    dbs = davies_bouldin_score(df_ref, labels)
    calinsky = calinski_harabasz_score(df_ref, labels)
    return [n_clusters, s, dbs, calinsky]


def Validar_cluster(n_groups, df, n_init=10,
    max_iter=300,
    random_state=101):
    df_metricas = pd.DataFrame(columns=['k','silhoutte', 'davies_bouldin', 'calinski_harabaz'])
    i = 0
    for k in n_groups:
        print(i)
        df_metricas.loc[i] = clustering_algorithm(k, df, n_init=n_init,
    max_iter=max_iter,
    random_state=random_state)
        i = i+1  
    return df_metricas

In [9]:
df =  datasets.load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [20]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [30]:
df['data']
##df['target']
df['target_names']
#df['feature_names']



array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [38]:
df_a = pd.DataFrame(df['data'], columns=df['feature_names'])

a_cond = [df['target'] == 0,
 df['target'] == 1,
 df['target'] == 2]


df_a['target'] = np.select(a_cond, df['target_names'])

df_a.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [58]:
df_a.columns = df_a.columns.str.replace(' \(cm\)','')
df_a.columns = df_a.columns.str.replace(' ', '_')
df_a.head()

C:\Users\andre\AppData\Local\Temp\ipykernel_24268\3438945556.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_a.columns = df_a.columns.str.replace(' \(cm\)','')


sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [59]:
df_ref = df_a.copy()
df_a.drop(columns=['target'], inplace=True)

In [61]:
# dados faltantes
df_a.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
dtype: int64

In [62]:
# normalizando os dados
df_normalize = Normalizer().fit_transform(df_a.values)
print(df_normalize)

[[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]
 [0.78417499 0.5663486  0.2468699  0.05808704]
 [0.78010936 0.57660257 0.23742459 0.0508767 ]
 [0.80218492 0.54548574 0.24065548 0.0320874 ]
 [0.80642366 0.5315065  0.25658935 0.03665562]
 [0.81803119 0.51752994 0.25041771 0.01669451]
 [0.80373519 0.55070744 0.22325977 0.02976797]
 [0.786991   0.55745196 0.26233033 0.03279129]
 [0.82307218 0.51442011 0.24006272 0.01714734]
 [0.8025126  0.55989251 0.20529392 0.01866308]
 [0.81120865 0.55945424 0.16783627 0.02797271]
 [0.77381111 0.59732787 0.2036345  0.05430253]
 [0.79428944 0.57365349 0.19121783 0.05883625]
 [0.80327412 0.55126656 0.22050662 0.04725142]
 [0.8068282  0.53788547 0.24063297 0.04246464]
 [0.77964883 0.58091482 0.22930848 0.0458617 ]
 [0.8173379  0.51462016 0.25731008 0.03027177]
 [0.78591858 

In [63]:
df_b = Validar_cluster([2,3,4,5,6,7,8,9,10,20,30,40,50], df_normalize, n_init=100,
    max_iter=3000,
    random_state=101)
df_b

0
1
2
3
4
5
6
7
8
9
10
11
12


k  silhoutte  davies_bouldin  calinski_harabaz
0    2.0   0.819244        0.240689       1633.998496
1    3.0   0.576326        0.644248       1446.997540
2    4.0   0.540241        0.789422       1157.648904
3    5.0   0.356338        1.065944       1012.196204
4    6.0   0.318187        1.102400        940.322842
5    7.0   0.297924        1.137313        853.099374
6    8.0   0.279275        1.157209        794.606143
7    9.0   0.296699        1.073354        762.811276
8   10.0   0.316349        1.013244        736.792388
9   20.0   0.298685        0.923757        616.496268
10  30.0   0.317222        0.799047        581.485942
11  40.0   0.324123        0.744084        599.236538
12  50.0   0.315817        0.600943        613.754529

In [64]:
df_b['ref'] = 'medidas'
print(df_b.groupby('ref').agg({'silhoutte': 'max', 'davies_bouldin': 'min', 'calinski_harabaz': 'max'}))
del df_b['ref']

         silhoutte  davies_bouldin  calinski_harabaz
ref                                                 
medidas   0.819244        0.240689       1633.998496


Pelos métodos considerados, estão apontando k-means estão sendo apontados dois grupos, por todas as métricas

In [72]:
# setando o modelo
model = KMeans(n_clusters = 2, n_init=100,
    max_iter=3000,
    random_state=101)

# aplicando o predict

y_pred = model.fit_predict(df_normalize)

In [66]:
df_normalize.shape

(150, 4)

## Validar a estabilidade dos clusters

Separamos a base em parte diferente, para avaliar se as métricas irão ter mudanças
se as metricas não tiverem grandes mudanças temos evidências que os cluster estão estáveis

In [67]:
random_data = np.random.rand(150, 4)

df_metricas = pd.DataFrame()
for k in [2]:
    df_metricas= df_metricas.append(pd.DataFrame(clustering_algorithm(k, random_data)).T)
df_metricas = df_metricas.rename(columns={0:'k', 1:'silhoutte', 2: 'davies_bouldin', 3:'calinski_harabaz'})
df_metricas.head()

C:\Users\andre\AppData\Local\Temp\ipykernel_24268\1797223719.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_metricas= df_metricas.append(pd.DataFrame(clustering_algorithm(k, random_data)).T)


k  silhoutte  davies_bouldin  calinski_harabaz
0  2.0   0.204016        1.832684         40.954119

In [68]:
set1, set2, set3 = np.array_split(df_normalize, 3)
print(clustering_algorithm(2, set1,n_init=100,
    max_iter=3000,
    random_state=101))
print(clustering_algorithm(2, set2,n_init=100,
    max_iter=3000,
    random_state=101))
print(clustering_algorithm(2, set3,n_init=100,
    max_iter=3000,
    random_state=101))

[2, 0.29161245640240324, 1.1882721437315007, 26.050635373250902]
[2, 0.34209050675163943, 1.1261539581693436, 28.401513817755625]
[2, 0.33214598664981343, 1.1228655231740996, 31.411751679228683]


Os dados não apresentam uma grande variação nas métricas, indicios de que os grupos estão bem definidos

In [74]:
df_centroids = pd.DataFrame(columns=['VARIAVEL', 'VARIANCIA'])
max = len(model.cluster_centers_[0])
for i in range(max):
    df_centroids.loc[i] = [df_a.columns.values[i], "{:4f}".format(model.cluster_centers_[:, i].var())]
    #print(df.columns.values[i], "\n{:4f}".format(kmeans.cluster_centers_[:, i].var()))

In [69]:
df_a['cluster'] = model.labels_
df_a.head()

sepal_length  sepal_width  petal_length  petal_width  cluster
0           5.1          3.5           1.4          0.2        1
1           4.9          3.0           1.4          0.2        1
2           4.7          3.2           1.3          0.2        1
3           4.6          3.1           1.5          0.2        1
4           5.0          3.6           1.4          0.2        1

In [75]:
df_centroids.sort_values('VARIANCIA', ascending=False)

VARIAVEL VARIANCIA
2  petal_length  0.027318
1   sepal_width  0.011357
3   petal_width  0.005840
0  sepal_length  0.001392

In [79]:
description = df_a[['petal_length','sepal_width','petal_width','sepal_length','cluster']].groupby('cluster')
n_clientes = description.size()
description = description.mean()
description['n_cliente'] = n_clientes
print(description.reset_index())

   cluster  petal_length  sepal_width  petal_width  sepal_length  n_cliente
0        0         4.906        2.872        1.676         6.262        100
1        1         1.462        3.428        0.246         5.006         50


[Fares Elmenshawii Notebook kaggle Kmeans Iris](https://www.kaggle.com/code/fareselmenshawii/kmeans-iris-clustering) - para ter ideias, layout bem bonito também

[Tetsuya Sasaki Notebook kaggle diferença kmeans e kmedoids](https://www.kaggle.com/code/sasakitetsuya/difference-between-kmeans-and-kmedoids)

[Khadijeh Abedi Clustering credicard](https://www.kaggle.com/code/abedi756/creditcard-clustering#K-Medoids) - Promissor caso kmeans não funcione